### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mansya** [jemskie93/bmi-calculator-android#1]
Hi, @iasjem I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by jemskie93** [comment]
Hello @mansya 

Sure. I would love to. This project is just for practice though but it would be a great help if you could help with graphic design.  Please let me know the details :)

**Comment by mansya** [comment]
I've designed a logo for your project. What do you think?
![bmi calculator](https://user-images.githubusercontent.com/33461607/40880193-d2c37ad0-669b-11e8-8fff-cf6201cff112.png)

**Comment by mansya** [comment]
isn't it interesting? if yes i will redesign
